import * as path from 'path';
import * as vscode from 'vscode';
import {
  readWorkspaceSettingValue,
  writeWorkspaceSettingValue,
} from '../settings/workspaceJsonSettings';

export const STUB_OVERRIDE_DIRECTORY_NAME = 'django-orm-intellisense-stubs';
export const STUB_OVERRIDE_RELATIVE_PATH = path.join(
  '.vscode',
  STUB_OVERRIDE_DIRECTORY_NAME
);

const STUB_PATH_SETTING_KEYS = [
  'python.analysis.stubPath',
  'basedpyright.analysis.stubPath',
] as const;

const GENERATED_HEADER =
  '# AUTO-GENERATED by Django ORM Intellisense. Do not edit by hand.\n' +
  '# This file is regenerated whenever the extension activates or\n' +
  '# the "Override Default Django Stubs" command is run.\n';

const README_CONTENT = `# Django ORM Intellisense stub overrides

This directory is generated automatically by the **Django ORM Intellisense**
VS Code extension. It shadows a narrow slice of the Django stubs that would
otherwise come from Pylance / Microsoft Python Extension / Pyright /
basedpyright, so this extension's hover, completion, and diagnostics can
take precedence for dynamic ORM surfaces.

- The folder uses PEP 561 partial stubs (\`py.typed\` contains \`partial\`).
  Pyright/Pylance use the overrides below and fall back to the real Django
  source for anything not shadowed.
- Do **not** commit this directory. It is regenerated from the extension.
- To opt out, run **Django ORM: Override Default Django Stubs** and pick
  *Restore* — the extension removes this directory and reverts the
  \`python.analysis.stubPath\` / \`basedpyright.analysis.stubPath\` settings.
`;

const GITIGNORE_CONTENT = `# Auto-generated stub overrides — safe to ignore
*
`;

interface StubFile {
  relativePath: string;
  contents: string;
}

const STUB_FILES: readonly StubFile[] = buildStubFiles();

export interface ApplyStubOverrideResult {
  stubDirectory: string;
  writtenFiles: string[];
  stubPathUpdates: Map<string, { previous?: string; next: string }>;
}

export async function applyStubOverrides(
  output: vscode.OutputChannel
): Promise<ApplyStubOverrideResult | undefined> {
  const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
  if (!workspaceFolder) {
    return undefined;
  }

  const stubDirectoryUri = vscode.Uri.joinPath(
    workspaceFolder.uri,
    '.vscode',
    STUB_OVERRIDE_DIRECTORY_NAME
  );
  const stubDirectoryFsPath = stubDirectoryUri.fsPath;

  const writtenFiles: string[] = [];
  for (const file of STUB_FILES) {
    const fileUri = vscode.Uri.joinPath(
      stubDirectoryUri,
      ...file.relativePath.split('/')
    );
    await vscode.workspace.fs.createDirectory(
      vscode.Uri.file(path.dirname(fileUri.fsPath))
    );
    await vscode.workspace.fs.writeFile(
      fileUri,
      Buffer.from(file.contents, 'utf8')
    );
    writtenFiles.push(path.relative(stubDirectoryFsPath, fileUri.fsPath));
  }

  const relativeStubPath = STUB_OVERRIDE_RELATIVE_PATH.split(path.sep).join('/');
  const stubPathUpdates = new Map<
    string,
    { previous?: string; next: string }
  >();

  for (const settingKey of STUB_PATH_SETTING_KEYS) {
    const previous =
      ((await readWorkspaceSettingValue(settingKey)) as string | undefined) ??
      undefined;
    if (previous === relativeStubPath) {
      continue;
    }

    await writeWorkspaceSettingValue(settingKey, relativeStubPath);
    stubPathUpdates.set(settingKey, { previous, next: relativeStubPath });
    output.appendLine(
      `[stubs] Set ${settingKey} = ${relativeStubPath} (was ${
        previous ?? '<unset>'
      })`
    );
  }

  output.appendLine(
    `[stubs] Generated ${writtenFiles.length} override file(s) under ${stubDirectoryFsPath}.`
  );

  await restartPythonLanguageServer(output);

  return {
    stubDirectory: stubDirectoryFsPath,
    writtenFiles,
    stubPathUpdates,
  };
}

export interface RevertStubOverrideResult {
  directoryRemoved: boolean;
  stubPathReverts: string[];
}

export async function revertStubOverrides(
  output: vscode.OutputChannel
): Promise<RevertStubOverrideResult | undefined> {
  const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
  if (!workspaceFolder) {
    return undefined;
  }

  const stubDirectoryUri = vscode.Uri.joinPath(
    workspaceFolder.uri,
    '.vscode',
    STUB_OVERRIDE_DIRECTORY_NAME
  );

  let directoryRemoved = false;
  try {
    await vscode.workspace.fs.delete(stubDirectoryUri, {
      recursive: true,
      useTrash: false,
    });
    directoryRemoved = true;
    output.appendLine(
      `[stubs] Removed override directory ${stubDirectoryUri.fsPath}.`
    );
  } catch (error) {
    if (!(error instanceof vscode.FileSystemError && error.code === 'FileNotFound')) {
      output.appendLine(
        `[stubs] Failed to remove override directory: ${String(error)}`
      );
    }
  }

  const relativeStubPath = STUB_OVERRIDE_RELATIVE_PATH.split(path.sep).join('/');
  const stubPathReverts: string[] = [];
  for (const settingKey of STUB_PATH_SETTING_KEYS) {
    const current =
      ((await readWorkspaceSettingValue(settingKey)) as string | undefined) ??
      undefined;
    if (current !== relativeStubPath) {
      continue;
    }
    await writeWorkspaceSettingValue(settingKey, undefined);
    stubPathReverts.push(settingKey);
    output.appendLine(`[stubs] Cleared ${settingKey}.`);
  }

  if (directoryRemoved || stubPathReverts.length > 0) {
    await restartPythonLanguageServer(output);
  }

  return { directoryRemoved, stubPathReverts };
}

const PYLANCE_RESTART_COMMANDS = [
  'python.analysis.restartLanguageServer',
  'pylance.restartServer',
  'python.restartLanguageServer',
  'pyright.restartserver',
  'basedpyright.restartserver',
] as const;

async function restartPythonLanguageServer(
  output: vscode.OutputChannel
): Promise<void> {
  const available = new Set(await vscode.commands.getCommands(true));
  for (const command of PYLANCE_RESTART_COMMANDS) {
    if (!available.has(command)) {
      continue;
    }
    try {
      await vscode.commands.executeCommand(command);
      output.appendLine(
        `[stubs] Triggered Python language server restart via ${command}.`
      );
      return;
    } catch (error) {
      output.appendLine(
        `[stubs] ${command} failed: ${String(error)}. Trying next candidate.`
      );
    }
  }
  output.appendLine(
    '[stubs] No Python language server restart command was available; stubPath changes may require a manual reload.'
  );
}

function buildStubFiles(): StubFile[] {
  return [
    { relativePath: 'README.md', contents: README_CONTENT },
    { relativePath: '.gitignore', contents: GITIGNORE_CONTENT },
    { relativePath: 'django/py.typed', contents: 'partial\n' },
    {
      relativePath: 'django/__init__.pyi',
      contents: `${GENERATED_HEADER}\n`,
    },
    {
      relativePath: 'django/db/__init__.pyi',
      contents: `${GENERATED_HEADER}\n`,
    },
    {
      relativePath: 'django/db/models/__init__.pyi',
      contents:
        `${GENERATED_HEADER}\n` +
        'from django.db.models.base import Model as Model\n' +
        'from django.db.models.manager import Manager as Manager\n' +
        'from django.db.models.manager import BaseManager as BaseManager\n' +
        'from django.db.models.query import QuerySet as QuerySet\n',
    },
    {
      relativePath: 'django/db/models/manager.pyi',
      contents: buildManagerStub(),
    },
    {
      relativePath: 'django/db/models/query.pyi',
      contents: buildQuerySetStub(),
    },
    {
      relativePath: 'django/db/models/base.pyi',
      contents: buildModelStub(),
    },
  ];
}

function buildManagerStub(): string {
  return `${GENERATED_HEADER}
from typing import Any, ClassVar, Generic, Iterable, Iterator, TypeVar

from django.db.models.query import QuerySet

_T = TypeVar("_T")

class BaseManager(Generic[_T]):
    model: ClassVar[Any]
    name: str
    creation_counter: int
    auto_created: bool
    use_in_migrations: bool

    def __init__(self) -> None: ...
    def contribute_to_class(self, *args: Any, **kwargs: Any) -> None: ...
    def get_queryset(self) -> QuerySet[_T]: ...
    def all(self) -> QuerySet[_T]: ...
    def none(self) -> QuerySet[_T]: ...
    def filter(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def exclude(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def get(self, *args: Any, **kwargs: Any) -> _T: ...
    def first(self) -> _T | None: ...
    def last(self) -> _T | None: ...
    def count(self) -> int: ...
    def exists(self) -> bool: ...
    def order_by(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def reverse(self) -> QuerySet[_T]: ...
    def distinct(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def values(self, *args: Any, **kwargs: Any) -> QuerySet[Any]: ...
    def values_list(self, *args: Any, **kwargs: Any) -> QuerySet[Any]: ...
    def dates(self, *args: Any, **kwargs: Any) -> QuerySet[Any]: ...
    def datetimes(self, *args: Any, **kwargs: Any) -> QuerySet[Any]: ...
    def annotate(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def alias(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def aggregate(self, *args: Any, **kwargs: Any) -> Any: ...
    def select_related(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def prefetch_related(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def only(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def defer(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def using(self, alias: str | None) -> QuerySet[_T]: ...
    def raw(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> _T: ...
    def get_or_create(self, *args: Any, **kwargs: Any) -> tuple[_T, bool]: ...
    def update_or_create(self, *args: Any, **kwargs: Any) -> tuple[_T, bool]: ...
    def update(self, *args: Any, **kwargs: Any) -> int: ...
    def delete(self) -> tuple[int, dict[str, int]]: ...
    def bulk_create(self, *args: Any, **kwargs: Any) -> list[_T]: ...
    def bulk_update(self, *args: Any, **kwargs: Any) -> int: ...
    def in_bulk(self, *args: Any, **kwargs: Any) -> dict[Any, _T]: ...
    def iterator(self, *args: Any, **kwargs: Any) -> Iterator[_T]: ...
    def latest(self, *args: Any, **kwargs: Any) -> _T: ...
    def earliest(self, *args: Any, **kwargs: Any) -> _T: ...
    def extra(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def complex_filter(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def union(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def intersection(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def difference(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def select_for_update(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def explain(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, name: str) -> Any: ...
    def __class_getitem__(cls, item: Any) -> Any: ...

class Manager(BaseManager[_T], Generic[_T]):
    def __init__(self) -> None: ...

class RelatedManager(Manager[_T], Generic[_T]):
    def add(self, *args: Any, **kwargs: Any) -> None: ...
    def remove(self, *args: Any, **kwargs: Any) -> None: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self) -> None: ...
`;
}

function buildQuerySetStub(): string {
  return `${GENERATED_HEADER}
from typing import Any, Generic, Iterable, Iterator, TypeVar

_T = TypeVar("_T")

class QuerySet(Generic[_T]):
    model: Any
    query: Any
    db: Any
    _result_cache: Any
    ordered: bool

    def __init__(
        self,
        model: Any = ...,
        query: Any = ...,
        using: Any = ...,
        hints: Any = ...,
    ) -> None: ...

    def all(self) -> QuerySet[_T]: ...
    def none(self) -> QuerySet[_T]: ...
    def filter(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def exclude(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def get(self, *args: Any, **kwargs: Any) -> _T: ...
    def first(self) -> _T | None: ...
    def last(self) -> _T | None: ...
    def count(self) -> int: ...
    def exists(self) -> bool: ...
    def order_by(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def reverse(self) -> QuerySet[_T]: ...
    def distinct(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def values(self, *args: Any, **kwargs: Any) -> QuerySet[Any]: ...
    def values_list(self, *args: Any, **kwargs: Any) -> QuerySet[Any]: ...
    def dates(self, *args: Any, **kwargs: Any) -> QuerySet[Any]: ...
    def datetimes(self, *args: Any, **kwargs: Any) -> QuerySet[Any]: ...
    def annotate(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def alias(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def aggregate(self, *args: Any, **kwargs: Any) -> Any: ...
    def select_related(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def prefetch_related(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def only(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def defer(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def using(self, alias: str | None) -> QuerySet[_T]: ...
    def raw(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> _T: ...
    def get_or_create(self, *args: Any, **kwargs: Any) -> tuple[_T, bool]: ...
    def update_or_create(self, *args: Any, **kwargs: Any) -> tuple[_T, bool]: ...
    def update(self, *args: Any, **kwargs: Any) -> int: ...
    def delete(self) -> tuple[int, dict[str, int]]: ...
    def bulk_create(self, *args: Any, **kwargs: Any) -> list[_T]: ...
    def bulk_update(self, *args: Any, **kwargs: Any) -> int: ...
    def in_bulk(self, *args: Any, **kwargs: Any) -> dict[Any, _T]: ...
    def iterator(self, *args: Any, **kwargs: Any) -> Iterator[_T]: ...
    def latest(self, *args: Any, **kwargs: Any) -> _T: ...
    def earliest(self, *args: Any, **kwargs: Any) -> _T: ...
    def extra(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def union(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def intersection(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def difference(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def select_for_update(self, *args: Any, **kwargs: Any) -> QuerySet[_T]: ...
    def explain(self, *args: Any, **kwargs: Any) -> str: ...

    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, item: Any) -> bool: ...
    def __getitem__(self, k: Any) -> Any: ...
    def __or__(self, other: Any) -> QuerySet[_T]: ...
    def __and__(self, other: Any) -> QuerySet[_T]: ...
    def __getattr__(self, name: str) -> Any: ...
    def __class_getitem__(cls, item: Any) -> Any: ...
`;
}

function buildModelStub(): string {
  return `${GENERATED_HEADER}
from typing import Any, ClassVar

from django.db.models.manager import Manager

class ModelState:
    db: Any
    adding: bool
    fields_cache: dict[str, Any]

class Model:
    pk: Any
    _meta: ClassVar[Any]
    _state: ModelState
    objects: ClassVar[Manager[Any]]
    DoesNotExist: ClassVar[type[Exception]]
    MultipleObjectsReturned: ClassVar[type[Exception]]

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __init_subclass__(cls, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, item: Any) -> Any: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def save_base(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, *args: Any, **kwargs: Any) -> tuple[int, dict[str, int]]: ...
    def refresh_from_db(self, *args: Any, **kwargs: Any) -> None: ...
    def full_clean(self, *args: Any, **kwargs: Any) -> None: ...
    def clean(self) -> None: ...
    def clean_fields(self, *args: Any, **kwargs: Any) -> None: ...
    def validate_unique(self, *args: Any, **kwargs: Any) -> None: ...
    def validate_constraints(self, *args: Any, **kwargs: Any) -> None: ...
    def get_absolute_url(self) -> str: ...
    def serializable_value(self, field_name: str) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
`;
}
